---
# Updates repository caches on RedHat and Ubuntu Servers. 

- hosts: all
  become: true
  pre_tasks:
    - name: update repo cache (RedHat)
      tags: always
      dnf:
        update_cache: 'yes'
      changed_when: false
      when: ansible_distribution == "RedHat"

    - name: update repo cache (Ubuntu)
      tags: always
      apt:
        update_cache: 'yes'
      changed_when: false
      when: ansible_distribution == "Ubuntu"


- hosts: workstations
  become: 'yes'
  tasks:
    - name: install unzip
      package:
        name: unzip
    - name: install terraform
      unarchive:
        src: >-
          https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: 'yes'
        mode: 493
        owner: root
        group: root


# Installs apache and php for Ubuntu and RedHat servers. Also copies data from default_site.html to index.html on the servers. 

- hosts: web_servers
  become: true
  tasks:
    - name: install apache and php for Ubuntu servers
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache and php for RedHat servers
      tags: 'apache,redhat,httpd'
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "RedHat"

    - name: start httpd (RedHat)
      tags: 'apache, centos, httpd'
      service:
        name: httpd
        state: started
        enabled: 'yes'
      when: ansible_distribution == "RedHat"
   
    - name: copy default html file for site
      tags: 'apache,apache2,httpd'
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 420

    - name: change e-mail address for admin
      tags: 'apache, centos, httpd'
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin somebody@somewhere.net
      when: ansible_distribution == "RedHat"
      register: httpd

    - name: restart httpd (RedHat)
      tags: apache,redhat,httpd
      service: 
        name: httpd
        state: restarted
      when: httpd.changed
 
#Install mariadb on Ubuntu and Redhat servers in the db_servers group
 
- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package (RedHat)
      tags: 'redhat,db,mariadb'
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "RedHat"
    - name: install mariadb package (Ubuntu)
      tags: 'db,mariadb,ubuntu'
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

#Creates dev user on all servers and assigns it to the root group

- hosts: all
  become: true
  tasks:
  
  - name: add ssh key
    tags: always
    authorized_key:
      user: dev
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCGdp6qKwuTl0PXAXeJXjUSsNZ3Myg5v73EW9A42TS7ZIKJfn/hpekgvGMBVcfRf05McqMPH/emIXOjC0N/ErvJ+sC5ixMeRB7fueH9e6my/WPZVoAopw+Xh9vxbgEqsKwEgPwukeVJAFam4Xdm/NZBMMlV3YH+OW0E2tOGZHo/EMYGSNUXm591DwChVWemqBJ4Hom5Ms3geIZdggoggUwNGl4lDDdp9OXjEP7kMFmfLNv1JULDRW1cerB6xpzyn/BMBLK1zsY9RVH1CTjSWQJwVvz/B9HDumosDPVI0fx9b7gM7LfOOTw0E4Nvn02YbUlxkEXcNN0IulgztzYxHSnd"
